#
# For each fengine, specify the host ip address (host_ip), destination port (dest_port),
# the antenna numbers it is processing (ants). 
#
# The following booleans can also be set- 
# if it needs to be initialized (init), 
# if you want to set noise (noise), 
# or test vector (tvg) input and if you want it to 
# send data over ethernet (eth).
#
# If a specific boolean task needs to be implemented on all fengines, you can 
# set it as a global parameter.
#
# NB: If fengine antennas are not specified, they will be alloted according the order in 
# which they are presented here.

# You can set the following global parameters for all fengines 
# or enable them for only some fengines. The global parameters 
# overrride the individual fengine settings.

# You can sync the fengines using an external PPS signal
# or manually using a software register. 
# Choices: 'pps', 'manual', False (default: 'pps')
sync: 'pps'

# The test vector generator can operate in multiple modes:
# 'const_ants' : Writes a different constant value 
#                to all channels of an antenna (both pols).
# 'const_pols' : Write a different constant value  
#                to both pols of an antenna.
# 'ramp'       : Write the same ramp to all pols.
# 'ramp_pols'  : Write a different ramp to each pol.
# False        : Do not set the test vector (default) 
tvg: False

# Turn on the noise generator for testing
noise: False

initialize: False

# Disable transmission for all fengines
eth: False

# Specify a full path to an F-Engine fpg files
fpgfile: '/home/jackh/hera_corr_f-master/snap_fengine/outputs/snap_fengine_2018-11-13_1236.fpg'

# Destination port for SNAP data
dest_port: 8511

fengines:
    heraNode23Snap0:
        phase_switch_index: 0
        ants: [0, 1, 2]
    heraNode23Snap1:
        phase_switch_index: 0
        ants: [3, 4, 5]
    heraNode23Snap2:
        phase_switch_index: 0
        ants: [6, 7, 8]
    heraNode23Snap3:
        phase_switch_index: 0
        ants: [9, 10, 11]

# Data is sent assuming a total of 32 Xengines and 
# a maximum of 48 channels per Xengine. If all the 
# 32 Xengines are not defined, the corresponding channels
# are not sent anywhere.
xengines:
    0:
        even:
           ip: "10.80.2.222"
           mac: 0x02020a0a0a28
        odd:
           ip: "10.80.2.222"
           mac: 0x02020a0a0a28
        chan_range: [1536, 1920]
    1:
        even:
           ip: "10.80.2.222"
           mac: 0x02020a0a0a28
        odd:
           ip: "10.80.2.222"
           mac: 0x02020a0a0a28
        chan_range: [1920, 2304]
    2:
        even:
           ip: "10.80.2.222"
           mac: 0x02020a0a0a28
        odd:
           ip: "10.80.2.222"
           mac: 0x02020a0a0a28
        chan_range: [2304, 2688]
    3:
        even:
           ip: "10.80.2.222"
           mac: 0x02020a0a0a28
        odd:
           ip: "10.80.2.222"
           mac: 0x02020a0a0a28
        chan_range: [2688, 3072]
    4:
        even:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a29
        odd:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a29
        chan_range: [3072, 3456]
    5:
        even:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a29
        odd:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a29
        chan_range: [3456, 3840]
    6:
        even:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a29
        odd:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a29
        chan_range: [3840, 4224]
    7:
        even:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a29
        odd:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a29
        chan_range: [4224, 4608]
    8:
        even:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a2a
        odd:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a2a
        chan_range: [4608, 4992]
    9:
        even:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a2a
        odd:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a2a
        chan_range: [4992, 5376]
    10:
        even:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a2a
        odd:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a2a
        chan_range: [5376, 5760]
    11:
        even:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a2a
        odd:
           ip: "10.80.2.223"
           mac: 0x02020a0a0a2a
        chan_range: [5760, 6144]
    12:
        even:
           ip: "10.80.2.224"
           mac: 0x02020a0a0a2b
        odd:
           ip: "10.80.2.224"
           mac: 0x02020a0a0a2b
        chan_range: [6144, 6528]
    13:
        even:
           ip: "10.80.2.224"
           mac: 0x02020a0a0a2b
        odd:
           ip: "10.80.2.224"
           mac: 0x02020a0a0a2b
        chan_range: [6528, 6912]
    14:
        even:
           ip: "10.80.2.224"
           mac: 0x02020a0a0a2b
        odd:
           ip: "10.80.2.224"
           mac: 0x02020a0a0a2b
        chan_range: [6912, 7296]
    15:
        even:
           ip: "10.80.2.224"
           mac: 0x02020a0a0a2b
        odd:
           ip: "10.80.2.224"
           mac: 0x02020a0a0a2b
        chan_range: [7296, 7680]
